apiVersion: v1
kind: Service
metadata:
  labels:
    app: sample-app
  name: flask-test
spec:
  externalTrafficPolicy: Cluster
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: sample-app
  type: LoadBalancer
